"options":
  "level_name":
    "default": "world"
    "type": "string"
    "description": "Name of the level, will be generated if it doesn't exist"
  "gamemode":
    "type": "string"
    "default": "survival"
    "description": "survival|creative"
  "allow_nether":
    "default": !!bool "true"
    "type": "boolean"
    "description": "Allow generation of the nether, true or false"
  "motd":
    "default": "Juju Powered Minecraft Server"
    "type": "string"
    "description": "Message of the day displayed to users in the server list"
  "max_players":
    "default": !!int "10"
    "type": "int"
    "description": "Maximum players allowed on the server"
  "spawn_animals":
    "default": !!bool "true"
    "type": "boolean"
    "description": "Generate animals, true or false"
  "spawn_monsters":
    "default": !!bool "true"
    "type": "boolean"
    "description": "Generate monsters, true or false"
  "difficulty":
    "default": !!int "1"
    "type": "int"
    "description": "Level of complexity 1-5"
  "server-port":
    "default": !!int "25565"
    "type": "int"
    "description": "Port for which Minecraft runs upon"
  "allow_flight":
    "default": !!bool "false"
    "type": "boolean"
    "description": "Allow players to fly, true or false"
  "enable_query":
    "default": !!bool "true"
    "type": "boolean"
    "description": "Allow quering the server, true or false"
  "query_port":
    "default": !!int "25566"
    "type": "int"
    "description": "Port for which Minecraft can be queried"
